name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      
#     - name: Checkout source code other
#       uses: actions/checkout@v3
#       with:
#         repository:  PhucLeChi/MyGithubAction
#         ref: 'dev'
#         path: DemoMyAction
        
#     - name: Run Custom Action A
#       uses: ./DemoMyAction/.github/myaction
#       with:
#         who-to-greet: 'LearnGitHubActions'
        
    - name: Run Custom Action B
      uses: PhucLeChi/MyGithubAction/testaction@dev
      with:
        who-to-greet: 'LearnGitHubActions'
        
    - name: Show log
      run: echo "Build number as env ${{ env.BUILD_NUMBER }}"
