name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: windows-latest
    
    env:
      PHYSICAL_PATH_FOR_APPLICATION: $env:SystemDrive\inetpub\wwwroot\api-test.rightprospectus.com\DocDistroTest
      MY_NAME: 'PhucLe'

    steps:
    - name: Show log
      run: echo "Build number as env ${{ env.PHYSICAL_PATH_FOR_APPLICATION }}"
#     - name: Checkout source code
#       uses: actions/checkout@v3
      
#     - name: Checkout source code other
#       uses: actions/checkout@v3
#       with:
#         repository:  PhucLeChi/MyGithubAction
#         ref: 'dev'
#         path: DemoMyAction
        
#     - name: Run Custom Action A
#       uses: PhucLeChi/MyGithubAction/.github/myaction@dev
#       with:
#         who-to-greet: 'LearnGitHubActions'
        
    - name: Run Custom Action B
      uses: PhucLeChi/MyGithubAction/testaction@dev
      with:
        who-to-greet: 'LearnGitHubActions'
        
    - name: Show log
      run: echo "Build number as env ${{ env.BUILD_NUMBER }}"

#     - name: Run Custom Action C
#       uses: PhucLeChi/MyGithubAction/.github/haha@feature/add-reused-workflow-build-and-package-dotnet
#       with:
#         who-to-greet: 'LearnGitHubActions'
        
    - name: Show log
      run: echo "Done"

  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Show log deploy
        run: echo "Build number for deploy ${{ env.BUILD_NUMBER }}"
      - name: Show log deploy 222
        run: echo "Build number for deploy ${{ needs.build.outputs.random-number }}"
