name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    
    env:
      PHYSICAL_PATH_FOR_APPLICATION: $env:SystemDrive\inetpub\wwwroot\api-test.rightprospectus.com\DocDistroTest
      MY_NAME: 'PhucLe'

    steps:
    - name: Show log
      run: echo "Build number as env ${{ env.PHYSICAL_PATH_FOR_APPLICATION }}"
        
    - name: Run Custom Action B
      id: build
      uses: PhucLeChi/MyGithubAction/testaction@dev
      with:
        who-to-greet: 'LearnGitHubActions'
        
    - name: Save output
      run: echo "BuildOutOut=1990" >> $env:GITHUB_OUTPUT
    
    outputs:
      random-number: ${{ env.BuildOutOut }}      
      build-number: ${{ steps.build.outputs.random-number }}

  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Show build out
        shell: pwsh
        run: echo "Build number for deploy ${{ needs.build.outputs.random-number }}"
      - name: Show build number
        shell: pwsh
        run: echo "Build number for deploy ${{ needs.build.outputs.build-number }}"
